### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by esparkman** [DanBrooker/file-icons#336] opened 2016-04-22 15:55 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v1.7.6

### Stack Trace

Uncaught TypeError: Cannot read property 'dataset' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

TypeError: Cannot read property 'dataset' of null
    at /Users/evansparkman/.atom/packages/file-icons/index.coffee:67:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1104:27)
    at TextEditor.module.exports.TextEditor.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:666:26)
    at Pane.module.exports.Pane.saveItemAs (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:742:16)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:726:21)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:23.3.0 application:new-file (atom-pane.pane.active)
     -0:20 core:save (atom-text-editor.editor.is-focused)
     -0:07.7.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tablr"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.7.6
indent-guide-improved, v1.4.5
language-babel, v2.17.3
linter, v1.11.4
linter-eslint, v7.2.1
sublime-panes, v0.2.5

# Dev
No dev packages
```

**Comment by fserb** [comment] 2016-04-23 05:19
Same here.

**Comment by Alhadis** [comment] 2016-04-23 12:08
Seems related to the `sublime-panes` package. I wasn't able to reproduce until I installed it.

**Comment by Alhadis** [comment] 2016-04-23 12:45
@esparkman / @fserb Could you two tell me the values of the following core settings?
1. Allow Pending Pane Items
2. Close Empty Windows
3. Remove Empty Panes

FYI, I noticed the [sublime-panes](https://github.com/ruhatch/sublime-panes) package hasn't been updated since August 2015, which is long before Atom added the pending items feature to its core.

**Comment by Alhadis** [comment] 2016-04-23 18:11
Right. Should be fixed.

I'll publish a patch release; please let me know if this happens again.

**Closed** 2016-04-23 18:10 UTC
Labels: bug
