### ISSUE TITLE
Latest update seems to break?

### ISSUE THREAD

**Issue by mikeerickson** [DanBrooker/file-icons#475] opened 2016-12-31 07:14 UTC
Is there a way to revert to a previous version?  I installed the latest build and all icons are show the generic icon now.   My only means of "fixing" is to uninstall the package and restart.

**Comment by jacobmischka** [comment] 2016-12-31 07:46
`apm install file-icons@1.7.25` will install the previous version

**Comment by mikeerickson** [comment] 2016-12-31 08:14
@jacobmishka awesome, thx. Will give that a try in the morning.

**Comment by Alhadis** [comment] 2016-12-31 08:50
@mikeerickson Are you using [Nuclide](https://github.com/facebook/nuclide)? This is a known issue that's currently being worked on. Will be fixed in the next version.

**Comment by mikeerickson** [comment] 2016-12-31 09:36
@Alhadis no, I am not using Nuclide

**Comment by Alhadis** [comment] 2016-12-31 09:38
Can you run `apm ls -i` and paste its output, please?

**Comment by ithil** [comment] 2016-12-31 10:03
I have the same issue. I'm using `seti-classic@0.10.1` as my theme; when I use another theme instead the icons show up again. `file-icons@1.7.25` worked fine though.

**Comment by Alhadis** [comment] 2016-12-31 10:37
@ithil Seti has had problems with file-icons in the past... we used a kludge earlier this year to forcefully override it with an extra CSS class. Seti later made that a non-issue by giving users a checkbox to toggle icons away, which you need to do in order for icons to display properly.

I don't know if [`seti-classic`](https://github.com/vermotr/seti-classic) has such a facility: but from the looks of it, I sorely doubt it...

**Comment by mikeerickson** [comment] 2016-12-31 18:28
@Alhadis I installed 1.7.25 ( `apm install file-icons@1.7.25` ) and now all is fine.

**Comment by mikeerickson** [comment] 2016-12-31 18:29
[36mBuilt-in Atom Packages[39m (89)
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.45.0
├── base16-tomorrow-dark-theme@1.3.0
├── base16-tomorrow-light-theme@1.3.0
├── one-dark-ui@1.6.2
├── one-light-ui@1.6.2
├── one-dark-syntax@1.5.0
├── one-light-syntax@1.5.0
├── solarized-dark-syntax@1.0.5
├── solarized-light-syntax@1.0.5
├── about@1.7.0
├── archive-view@0.62.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.13.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.4
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── bookmarks@0.42.0
├── bracket-matcher@0.82.2
├── command-palette@0.39.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.0
├── find-and-replace@0.202.2
├── fuzzy-finder@1.4.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.2
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.0
├── link@0.31.2
├── markdown-preview@0.158.8
├── metrics@1.1.2
├── notifications@0.65.1
├── open-on-github@1.2.1
├── package-generator@1.0.1
├── settings-view@0.243.1
├── snippets@1.0.4
├── spell-check@0.68.4
├── status-bar@1.4.1
├── styleguide@0.47.2
├── symbols-view@0.113.1
├── tabs@0.103.0
├── timecop@0.33.2
├── tree-view@0.210.0
├── update-package-dependencies@0.10.0
├── welcome@0.35.1
├── whitespace@0.35.0
├── wrap-guide@0.38.2
├── language-c@0.54.0
├── language-clojure@0.22.1
├── language-coffee-script@0.48.0
├── language-csharp@0.13.0
├── language-css@0.40.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.43.0
├── language-html@0.47.1
├── language-hyperlink@0.16.1
├── language-java@0.24.0
├── language-javascript@0.122.0
├── language-json@0.18.3
├── language-less@0.29.6
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.3
├── language-property-list@0.8.0
├── language-python@0.45.1
├── language-ruby@0.70.2
├── language-ruby-on-rails@0.25.1
├── language-sass@0.57.0
├── language-shellscript@0.23.0
├── language-source@0.9.0
├── language-sql@0.25.0
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.12
└── language-yaml@0.27.1

[36mCommunity Packages (80)[39m /Users/mikee/.atom/packages
├── Atom-Syntax-highlighting-for-Sass@0.5.0
├── Sass-Syntax-Highlight@0.1.1
├── Sublime-Style-Column-Selection@1.7.2
├── advanced-new-file@0.5.0
├── advanced-open-file@0.16.4
├── aligner@0.22.3
├── aligner-css@1.2.0
├── aligner-scss@1.1.0
├── alignment@1.1.5
├── atom-alignment@0.12.1
├── atom-beautify@0.29.16
├── atom-json-color@0.4.2
├── atom-material-ui@1.3.8
├── atom-terminal@0.8.0
├── autocomplete-modules@1.6.7
├── autocomplete-sass@0.1.0
├── awesome-tool-bar@0.4.3
├── best-js-snippets@4.1.0
├── bracket-matcher-highlight@0.5.0
├── cobalt2-syntax@0.4.0
├── color-picker@2.2.3
├── copy-path@0.4.0
├── css-snippets@1.1.0
├── dash@1.7.0
├── duplicate-line-or-selection@0.9.0
├── emmet@2.4.3
├── es6-snippets@0.3.0
├── expand-region@0.2.6
├── file-icons@1.7.25
├── filesize@2.0.0
├── fonts@1.7.0
├── gist@0.3.1
├── gist-it@0.9.1
├── git-control@0.8.2
├── git-log@0.4.1
├── git-plus@7.0.4
├── git-time-machine@1.5.4
├── goto-definition@1.1.19
├── highlight-line@0.11.2
├── highlight-selected@0.11.2
├── indent-guide-improved@1.4.11
├── ir-black-k-syntax@0.1.0
├── javascript-snippets@1.2.1
├── jumpy@3.1.3
├── linter@1.11.18
├── linter-csslint@1.3.3
├── linter-eslint@8.0.0
├── linter-sass-lint@1.7.4
├── local-history@3.4.1
├── material-ui@1.0.9
├── merge-conflicts@1.4.4
├── minimap@4.25.7
├── minimap-highlight-selected@4.4.0
├── node-debugger@1.9.2
├── open-in-browsers@0.0.19
├── open-recent@5.0.0
├── pigments@0.37.0
├── platformio-ide-terminal@2.2.2
├── pretty-json@1.6.1
├── project-plus@0.9.0
├── quick-highlight@0.6.1
├── recent-files-fuzzy-finder@0.2.4
├── script@3.13.0
├── select-rectangle@1.0.2
├── set-syntax@0.3.2
├── seti-classic@0.10.1
├── seti-classic-syntax@0.5.0
├── seti-syntax@1.0.1
├── seti-ui@1.4.0
├── seti-ui-beta@0.1.1
├── sort-lines@0.14.0
├── split-diff@1.1.0
├── synced-sidebar@0.4.3
├── toggle-quotes@1.0.0
├── tool-bar@1.0.1
├── tool-bar-almighty@0.8.1
├── tree-view-open-files@0.3.0
├── turbo-javascript@1.4.0
├── wakatime@6.0.12
└── wordcount@2.10.2

└── (empty)

**Comment by avindra** [comment] 2016-12-31 19:38
Dupe of #471

**Comment by jacobmischka** [comment] 2016-12-31 20:09
Not really, he's not using nuclide. This issue is about seti.

**Comment by kennetpostigo** [comment] 2017-01-02 00:38
I just installed atom, nuclide, and file-icons and the icons don't appear. However, if I disable nuclide the icons appear.

**Comment by Alhadis** [comment] 2017-01-02 09:22
@ihackalot Yikes, fixed. Just cut a patch for that now.

@kennetpostigo Yes, the Nuclide thing is a known issue, but there's actually nothing we can do about it on our end. The Nuclide team need to update their package's code to use Atom's services API.

**Comment by Alhadis** [comment] 2017-01-03 07:17
@mikeerickson The author of the Seti theme merged my PR, so I'm closing this.

If anybody is experiencing new errors that aren't reported, please file new issues so we can keep better track. Thanks!

**Closed by Alhadis** 2017-01-03 07:17 UTC
