### ISSUE TITLE
Change color of icons to contrast with git statuses

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [DanBrooker/file-icons#341] opened 2016-04-24 19:04 UTC
When I have .json files in with some files that are modified in git, the modified files and the json file icon are the same color. 

How hard would it be to change this?

**Comment by Alhadis** [comment] 2016-04-24 19:38
Not really hard. Just a simple matter of refining the colour that's applied to modified files that use the `.medium-yellow` swatch.

The question becomes whether we should use a darker or lighter shade of orange to represent these particular files, though.

**Comment by Alhadis** [comment] 2016-05-03 18:22
I was asking for your thoughts on the matter, my good sir. ;-)

**Comment by The-Penultimate-Defenestrator** [comment] 2016-05-03 18:23
I think the majority of people use dark themes, so I think lighter.

**Comment by Alhadis** [comment] 2016-05-03 18:25
Alright, shall do.

FYI, v2.0.0 should make adjusting colours a *hell* of a lot easier.

**Comment by Alhadis** [comment] 2016-05-03 18:55
Eh, lightening an already light colour isn't really noticeable (even in a dark theme)... using a darker shade might be the way to go, actually.

**Comment by The-Penultimate-Defenestrator** [comment] 2016-05-03 19:19
Ok. I don't have a strong opinion

**Comment by Alhadis** [comment] 2016-05-03 19:31
Done, mate. =) Will be included in the next release.

**Comment by The-Penultimate-Defenestrator** [comment] 2016-05-03 19:31
Thanks :)

**Closed** 2016-05-03 19:30 UTC

**Comment by AriaFallah** [comment] 2016-05-06 14:17
@Alhadis this shifts the color of icons that haven't been changed for me. As soon as I edited one file, every single file in the folder shifted to a light yellow.

**Comment by Alhadis** [comment] 2016-05-06 14:17
Could you take a screenshot of the tree view, please?

**Comment by AriaFallah** [comment] 2016-05-06 14:18
<img width="233" alt="screen shot 2016-05-06 at 10 18 20 am" src="https://cloud.githubusercontent.com/assets/9424976/15075724/ec3ef070-1373-11e6-83ab-8f58537f9689.png">

**Comment by Alhadis** [comment] 2016-05-06 14:23
CRIPES, that's bad. I forgot about folders being marked as modified too... `/facepalm`

Okay, fixing immediately. Will push out a hotfix.

**Comment by AriaFallah** [comment] 2016-05-06 14:24
@Alhadis no worries. Thanks for the quick responses!

**Comment by Alhadis** [comment] 2016-05-06 14:29
@AriaFallah, I can't reproduce this. Can you open the developer tools and inspect one of the wrongly-highlighted files, please? Tell me if the containing `<li>` node has the `status-modified` class added.

If not, it might have something to do with the theme's styling (or a line in your user stylesheet). If not, it might be another package at fault - could you give me a list of what you currently have installed?

I've tried all permutations of this package's options, and none of them are reproducing the error.

**Comment by AriaFallah** [comment] 2016-05-06 14:31
@Alhadis this is the responsible css selector it seems `.list-tree li:not(.list-nested-item).status-modified`

**Comment by Alhadis** [comment] 2016-05-06 14:33
That's not coming from this package, then. There isn't even a line that contains `list-nested-item` in this package's CSS.

**Comment by AriaFallah** [comment] 2016-05-06 14:34
@Alhadis yeah I need to figure out what's wrong actually. Something weird is happening in the repo right now. Every file I select is shown as modified, but then shows up as not modified when I select another file.

**Comment by Alhadis** [comment] 2016-05-06 14:35
Tell me what themes you're using, and what packages are installed. I'll help you find the catalyst.

**Comment by AriaFallah** [comment] 2016-05-06 14:42
@Alhadis alright after doing some more inspection I think the problem is that I didn't show you the full picture.

The modified folder is part of a larger folder. If that larger folder is the root folder then the problem occurs, but if I just open the project with the structure I screenshotted as root then the problem doesn't occur. So I think it's root directory related.

Also I gave you the wrong selector before. According to the dev tools this is the responsible selector:

```css
.status-modified .file-icons-tab-pane-icon atom-pane .tab-bar .tab
.title[data-path][data-name$=".json"]:before, .status-modified
.icon-file-text[data-name$=".json"]:before, .status-modified
.icon-file-binary[data-name$=".json"]:before, .status-modified
.theme-flatland-dark-ui .icon-file-text[data-name$=".json"]:before,
.status-modified .theme-flatland-dark-ui .icon-book[data-name$=".json"]:before
```

Also if it's theme related I'm using, which I don't think is the case, I'm using `One Dark` for UI and `Base16 Tomorrow Dark` for syntax.

**Comment by Alhadis** [comment] 2016-05-06 14:47
Files are only marked as modified or new if the project's root folder is a Git repository, yes. I'll have a look.

What about the list of packages you have installed? Can you run `apm list` in your terminal and show me the output?

(**Hint:** if you're on Mac OS, you can save yourself selecting the terminal's feedback by running `apm list | pbcopy` instead).

**Comment by AriaFallah** [comment] 2016-05-06 14:48
Oh boy:

Built-in Atom Packages
├── about@1.4.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.29.1
├── autocomplete-snippets@1.10.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.38.2
├── bracket-matcher@0.81.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.199.0
├── fuzzy-finder@1.0.5
├── git-diff@1.0.1
├── go-to-line@0.30.0
├── grammar-selector@0.48.1
├── image-view@0.57.0
├── incompatible-packages@0.25.1
├── keybinding-resolver@0.35.0
├── language-c@0.51.1
├── language-clojure@0.20.0
├── language-coffee-script@0.46.1
├── language-csharp@0.12.0
├── language-css@0.36.0
├── language-gfm@0.85.0
├── language-git@0.12.1
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-json@0.17.6
├── language-less@0.29.0
├── language-make@0.21.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.32.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.43.0
├── language-ruby@0.68.3
├── language-ruby-on-rails@0.25.0
├── language-sass@0.46.0
├── language-shellscript@0.21.0
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.1
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.4
├── language-yaml@0.25.1
├── line-ending-selector@0.3.1
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.63.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.2.0
├── one-light-syntax@1.2.0
├── one-light-ui@1.2.0
├── open-on-github@1.0.1
├── package-generator@1.0.0
├── settings-view@0.235.1
├── snippets@1.0.1
├── solarized-dark-syntax@1.0.0
├── solarized-light-syntax@1.0.0
├── spell-check@0.67.0
├── status-bar@1.1.2
├── styleguide@0.45.2
├── symbols-view@0.112.0
├── tabs@0.92.0
├── timecop@0.33.1
├── tree-view@0.205.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages
├── advanced-open-file@0.16.2
├── atom-alignment@0.12.1
├── atom-beautify@0.29.7
├── atom-typescript@8.9.1
├── atomic-emacs@0.9.1
├── autocomplete-clang@0.9.3
├── autocomplete-ctags
├── autocomplete-emojis@2.3.0
├── autocomplete-haskell@0.6.5
├── autocomplete-python@1.7.2
├── base16-syntax@1.7.0
├── color-picker@2.1.1
├── csscomb@0.3.1
├── django-templates@0.5.0
├── expand-region@0.2.4
├── file-icons@1.7.9
├── filesize@0.4.2
├── flow-ide@1.0.6
├── git-plus@5.13.4
├── haskell-ghc-mod@1.12.2
├── ide-haskell@1.6.2
├── ide-haskell-cabal@1.2.2
├── ide-haskell-hasktags@0.0.4
├── language-babel@2.19.4
├── language-docker@1.1.6
├── language-ember-htmlbars@0.3.0
├── language-fish-shell@1.0.3
├── language-haskell@1.7.15
├── language-latex@0.6.1
├── language-lisp@0.2.0
├── language-r@0.4.1
├── language-racket@0.4.0
├── latex@0.32.0
├── linter@1.11.4
├── linter-clang@3.4.4
├── linter-eslint@7.2.2
├── linter-flake8@1.13.0
├── linter-jsonlint@1.2.5
├── markdown-preview-plus@2.4.0
├── merge-conflicts@1.4.2
├── pdf-view@0.50.0
├── pigments@0.26.2
├── project-manager@2.9.7
├── python-autopep8@0.1.3
├── script@3.7.1
└── shell-it@0.2.1

└── (empty)

**Comment by Alhadis** [comment] 2016-05-06 14:50
Erh, [pastebin please](http://pastebin.com/). =)

**Comment by AriaFallah** [comment] 2016-05-06 14:51
@Alhadis edited

**Comment by Alhadis** [comment] 2016-05-06 14:59
Does this still happen if you disable every package *except* for File Icons?

If so, it's definitely related. If not, you can reactivate them one-by-one until you trigger it...

This is really puzzling though, and it's kinda frustrating that I can't reproduce it... :S

**Comment by AriaFallah** [comment] 2016-05-06 15:12
@Alhadis I disabled everything including atom's own packages (including settings-view 😅) ...still not solved 😢.

For me the steps to reproduce are this:

1. Open a project under git version control.
2. Modify a file in a folder not at the root level.

**Comment by Alhadis** [comment] 2016-05-06 15:17
Oh *derp*, I know what it is. It's [this](https://github.com/DanBrooker/file-icons/blob/master/styles/colors.less#L96), which was indeed added to fix this issue.

I've said it before, but I'll say it again: fuck precompilers, fuck Less, fuck Sass, and fuck all that bullshit for introducing problems like these that shouldn't have to exist.

Fixing now. Sorry to make you jump all those hurdles. :(

**Comment by Alhadis** [comment] 2016-05-06 15:18
The reason I couldn't reproduce the error, of course, was that I was modifying files that weren't using the `.medium-yellow` colour swatch.

**Comment by Alhadis** [comment] 2016-05-06 15:25
Wait, I spoke too soon (but still stand by my hatred of precompilers). Modifying a `.js` file doesn't help either, but I still suspect the issue is related (since that's all it *could* be, really). Does this still happen if you modify, say, a `.css` file?

**Comment by AriaFallah** [comment] 2016-05-06 15:28
@Alhadis nope. I tried txt and json, but no luck.

**Comment by AriaFallah** [comment] 2016-05-06 15:32
Also the problem has to be in `v1.7.9` because reverting to `v1.7.8` fixed it.

**Comment by Alhadis** [comment] 2016-05-06 15:35
Could you file a new issue for this, please? I just noticed how long this thread's gotten...

**Comment by AriaFallah** [comment] 2016-05-06 15:37
#352

**Comment by Alhadis** [comment] 2016-05-07 01:17
@The-Penultimate-Defenestrator Just letting you know we've had to revert this; the colour-correction will have to wait until v2, because there's no way of doing this without raising these weird edge cases.

**Comment by The-Penultimate-Defenestrator** [comment] 2016-05-07 11:18
Ok. It's fine. Thanks.
