### ISSUE TITLE
Tabs icon does not update

### ISSUE THREAD

**Issue by montogeek** [DanBrooker/file-icons#235] opened 2015-11-24 23:52 UTC
Hi!

When you have a file open, then rename the file extension the icon on the tab does not get updated, you have to reload the file.

My guess is that it's some Atom restriction.

**Comment by ckross01** [comment] 2015-11-25 02:28
Thanks for submitting an issue!

I believe this is a duplicate of #193 if that is different than what you are experiencing let me know. If not we can close this issue.

**Closed** 2015-11-25 02:51 UTC
Labels: duplicate
