### ISSUE TITLE
Title tab content is re-positioned when package is active.

### ISSUE THREAD

**Issue by alice-em** [DanBrooker/file-icons#230] opened 2015-11-16 01:59 UTC
// 1.6.11 on Fedora23 :: Linux 

When enabled, the content of the title tabs rearranges itself so that the icon is half missing, and the title moves up a few pixels.  I've attached an image to specify.

http://imgur.com/eLzBJEm

**Comment by Alhadis** [comment] 2016-02-24 18:45
Is this still happening for you? There've been a few updates recently that affected the styling of the file-tab pane.

**Comment by Alhadis** [comment] 2016-04-21 11:18
@alice-em I'm marking this as closed as I can't reproduce; but if this is still happening in the latest version, please let me know.

**Closed by Alhadis** 2016-04-21 11:18 UTC

**Comment by alice-em** [comment] 2016-04-22 02:33
Sorry for not being on top of this.

I have a feeling the glitch was caused by the theme I was using and not by file-icons.  I can't tell you which theme it was (I've been through a few), but I think it was a CSS error inside the theme package.

**Comment by Alhadis** [comment] 2016-04-22 02:34
Quite possibly. There've been a few theme-specific fixes since this was filed, which is why I asked.

And no problem. =)
