### ISSUE TITLE
Vagrantfile icon is blurry

### ISSUE THREAD

**Issue by alejandroandreu** [DanBrooker/file-icons#387] opened 2016-06-13 08:46 UTC
Hi,

I added a Vagrantfile to a project and the "V" icon does not have a good definition compared to the rest of the icons included in this amazing package.

![snapshot3](https://cloud.githubusercontent.com/assets/2419181/16001716/feaaa418-3153-11e6-9541-e06f895783c3.png)

Thanks!

**Comment by Alhadis** [comment] 2016-06-13 08:49
Duplicate of #381: it'll be fixed in the next release. =)

That blurriness was supposed to be part of the logo, but I can see how people think it's a bug...

**Closed by Alhadis** 2016-06-13 08:49 UTC

**Comment by alejandroandreu** [comment] 2016-06-13 09:50
Thanks! I couldn't see #381 as it was closed already. Keep up the good work! :smile:
